### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by harisgen79** [objectbox/objectbox-go#10]
After executing $ go get github.com/objectbox/objectbox-go/... in terminal I get the following error:

pi@raspberrypi:~ $ go get github.com/objectbox/objectbox-go/...
\# github.com/objectbox/objectbox-go/objectbox
/usr/bin/ld: cannot find -lobjectbox
/usr/bin/ld: cannot find -lobjectbox
/usr/bin/ld: cannot find -lobjectbox
/usr/bin/ld: cannot find -lobjectbox
/usr/bin/ld: cannot find -lobjectbox
/usr/bin/ld: cannot find -lobjectbox
/usr/bin/ld: cannot find -lobjectbox
/usr/bin/ld: cannot find -lobjectbox
/usr/bin/ld: cannot find -lobjectbox
/usr/bin/ld: cannot find -lobjectbox
collect2: error: ld returned 1 exit status

As you can see, I'm using Raspbian on Raspberry Pi 3 model B V1.2. 
Any suggestions?
Thanks.

**Comment by vaind** [comment]
It seems like your objectbox-c library (binary) installation is broken. Could you try to reinstall and see if the problem persists? https://golang.objectbox.io/install#objectbox-library

```
bash <(curl -s https://raw.githubusercontent.com/objectbox/objectbox-c/master/download.sh)
```
type 'Y' when it wants to install the library to /usr/local/lib

**Comment by harisgen79** [comment]
Thanks, it worked.

**Comment by vaind** [comment]
You're welcome. Closing the issue, feel free to follow up in case of any other problems.
