### ISSUE TITLE
What is the best way of dealing with multiple models.

### ISSUE THREAD

**Issue by OGKevin** [objectbox/objectbox-go#15]
I was thinking of passing 1 object box instance down as dependency to methods. But i soon reliased that you need to create 1 objectbox per model. e.g. the following will not work: 

```go
	ob, err := objectbox.NewBuilder().
		Directory(dir).
		Model(package1.ObjectBoxModel()).
		Model(package2.ObjectBoxModel()).
		Build()
```

```go
box1 := BoxForModel1(ob)
box2 := BoxForModel2(ob)
```

And this is because of 

```go
	builder.Error = model.validate()
	if builder.Error != nil {
		builder.model = nil
	} else {
		builder.model = model // this line
	}
```

So as i understand, i need to create 1 objectbox + 1 BxoForMODEL with one ObjectBox per model. Whith this being said, what is the recomanded way to deal with mutliple models? Instead of passing down from top of the stack just create these  2 instances every single time i need it ? I rather have 1 thing to pass down that has everything e.g. the sql driver (objecbox) which you create repositories (BoxForMODEL) with. 🤔 

Also is it an idea to return an error when you try to regiester more then 1 model? Causes less confusion later when you get errors like 

>  Could not create query - please check your query conditions: unordered_map::at: key not found

**Comment by OGKevin** [comment]
I think i might have solved my problem with https://godoc.org/go.uber.org/fx :)

**Comment by vaind** [comment]
See https://github.com/objectbox/objectbox-go/issues/14#issuecomment-518551516 for a potential answer to this question and let me know if that helps.

Thanks for the error suggestion, I'll have a look if we can do something about it.

**Comment by OGKevin** [comment]
I ended up declaring all my models in a `models` package. This seems to be the best solution.
