### ISSUE TITLE
Query: OR condition

### ISSUE THREAD

**Issue by alecpetrosky** [objectbox/objectbox-go#26]
I know  that  Java's version of Objectbox supports OR condition in queries. Does Go version offers the same functionality at the moment?

**Comment by vaind** [comment]
Yes, they're combined using `objectbox.Any()` to create a "condition group", see https://github.com/objectbox/objectbox-go/blob/master/test/query_test.go#L660

**Comment by alecpetrosky** [comment]
Thank you very much for the clarification!
