### ISSUE TITLE
go generate not working

### ISSUE THREAD

**Issue by phrozen** [objectbox/objectbox-go#4]
I'm in Windows 10, I installed everything as per the docs, but the go generate command does nothing, just runs and exits normally, but there are no files generated. I even try to run objectbox-gogen directly, but it prints out the help everytime even after specifying the -source file via flags, it just keeps printing the help.

Any thoughts on how to fix?

**Comment by dlugos** [comment]
Would you mind executing go generate on the objectbox-go repo? There are a few entities so you should see a message that it's generating the code for them.

either navigate to the objectbox-go dir in the GOPATH and run `go generate ./...`
or this should work as well: `go generate github.com/objectbox/objectbox-go/...`
