### ISSUE TITLE
Performance Benchmarks page has broken images

### ISSUE THREAD

**Issue by shawncatz** [objectbox/objectbox-go#51]
#### Description
[Performance Benchmarks](https://objectbox.io/go-1-0-release-and-performance-benchmarks/) page has broken images. I didn't see any existing reports of this.

![Screenshot 2024-02-20 at 2 58 52 PM](https://github.com/objectbox/objectbox-go/assets/1661830/ed468cb3-5c33-42a6-9a51-66ef91b9df0f)

When trying to load an [image](https://lh5.googleusercontent.com/C25h8fv86OcQUmkv4vRqUnPmesMkW7977iTBQHUolP4Z4uLTHOolNDKnc7OwCtHauLYTENv2dNp_66J46Tw_ieX2PuUnLDRyLpbEvRbck_JIW5psuBAEocT6znur3yyBM9G3NfTS) directly, it shows a 403 error from Google:

![Screenshot 2024-02-20 at 2 59 44 PM](https://github.com/objectbox/objectbox-go/assets/1661830/d413bf20-7b3d-45ab-b58b-a716e465a04c)

**Comment by greenrobot-team** [comment]
Appears to be resolved.
